### ISSUE TITLE
ESP 12 Compatibility?

### ISSUE THREAD

**Issue by Sumgit91** [witnessmenow/ESP8266-IR-Remote-Example#2]
Hi, Does this work on ESP 12, Please reply, waiting for your answer

**Comment by cooljimy84** [comment]
seems to work on my esp8266 nodemcu 12 clone, tho i still have to use version 1 library as i've not worked out how to convert it to use version 2...

**Comment by joeybab3** [comment]
It works on some esp8266's, they might just label the pins differently.
